#!name= 什么值得买去广告
#!desc= 什么值得买去广告
#!homepage= https://github.com/blackmatrix7
#!author= blackmatrix7
#!url= https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.qxrewrite


[URL Rewrite]
# 好价详情页去广告
^https?:\/\/haojia\.m\.smzdm\.com\/detail_modul\/other_modul _ reject
# 好价详情页红包小助手
^https?:\/\/haojia\.m\.smzdm\.com\/detail_modul\/user_related_modul _ reject
# Wiki(618晒物活动推广，将来可能不是广告)
^https?:\/\/haojia\.m\.smzdm\.com\/detail_modul\/wiki_related_modul _ reject


[Script]
# 开屏去广告
开屏去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/app-api\.smzdm\.com\/util\/loading,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 首页去广告
首页去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/homepage-api\.smzdm\.com\/v3\/home,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 好价去广告
好价去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/haojia-api\.smzdm\.com\/home\/list,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 好价详情页去广告
好价详情页去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/haojia\.m\.smzdm\.com\/detail_modul\/article_releated_modul,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 百科去广告
百科去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/baike-api\.smzdm\.com\/home_v3\/list,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 搜索结果去广告
搜索结果去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/s-api\.smzdm\.com\/sou\/list_v10,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 搜索标签去广告
搜索标签去广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/s-api\.smzdm\.com\/sou\/filter\/tags\/hot_tags,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# 值会员权益中心banner广告
值会员权益中心banner广告 = type=http-response,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_remove_ads.js,pattern=^https?:\/\/zhiyou\.m\.smzdm\.com\/user\/vip\/ajax_get_banner,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true


[MITM]
hostname = %APPEND% app-api.smzdm.com,homepage-api.smzdm.com,haojia-api.smzdm.com,haojia.m.smzdm.com,baike-api.smzdm.com,s-api.smzdm.com,zhiyou.m.smzdm.com