#!name= 微信解锁被屏蔽的URL
#!desc= 微信解锁被屏蔽的URL
#!homepage= https://github.com/zZPiglet
#!author= zZPiglet
#!url= https://raw.githubusercontent.com/wen704/rules/main/UnblockURLinWeChat.module

# 原作者链接 https://raw.githubusercontent.com/zZPiglet/Task/master/UnblockURLinWeChat.conf

[Script]
#跳过中间界面，支付宝链接、被封禁链接进行通知弹窗跳转，在微信中用快照显示被封禁的链接（可选），在微信中进行强制重定向（可选），群聊 / 扫码均可使用，可选项可在脚本 2、3 行更改，也可在 BoxJs 中更改。
微信解锁被屏蔽的URL = type=http-response,script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js,pattern=^https?:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# 自用历史脚本
# 微信链接快捷跳转 = type=http-response,pattern=^https?:\/\/weixin110\.qq\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi,script-path=https://raw.githubusercontent.com/HotKids/Rules/master/Script/weixin110.js,requires-body=1,script-update-interval=86400
微信公众号去广告= type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad ,requires-body=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/Wechat.js,script-update-interval=86400

[MITM]
hostname = %APPEND% weixin110.qq.com, security.wechat.com, mp.weixin.qq.com