#!name= 微信解锁被屏蔽的URL
#!desc= 微信解锁被屏蔽的URL
#!homepage= https://github.com/zZPiglet
#!author= zZPiglet
#!url= https://github.com/zZPiglet/Task/blob/master/UnblockURLinWeChat.conf

[Script]
# 解锁被屏蔽的URL
解锁被屏蔽的URL = type=http-response,script-path=https://raw.githubusercontent.com/wen704/rules/master/js/UnblockURLinWeChat.js,pattern=^https?:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% weixin110.qq.com,security.wechat.com
