#!name= 高德地图净化[墨鱼版]
#!desc= 使用前请卸载高德地图，挂载脚本然后使用
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/Amap.module

// ==UserScript==
// @ScriptName        高德地图净化[墨鱼版]
// @Author            @ddgksf2013
// @ForHelp           若有屏蔽广告的需求，可公众号后台回复APP名称
// @WechatID          公众号墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2023-04-25
// @Suitable          自行观看“# > ”注释内容
// @Attention         使用前请卸载高德地图，挂载脚本然后使用
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.22
// @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/Amap.conf
// ==/UserScript==

[URL Rewrite]
# > 高德地图_路线规划下方广告@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/card-service-route-plan\? _ reject-dict
# > 高德地图_Tip请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/boss\/order_web\/\w{8}_information _ reject-200
# > 高德地图_通用广告请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/asa\/ads_attribution _ reject
# > 高德地图_搜索框scene@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/shield\/scene\/recommend _ reject-dict
# > 高德地图_首页左上角gif@ddgksf2013
^https?:\/\/.*\.amap\.com\/uploadimg\/\w+\.gif _ reject-img
# > 高德地图_左下天气@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/valueadded\/weather _ reject-dict

[Script]
# > 高德地图_amdc处理[Anti已将Amdc分流删除,故更换屏蔽策略]@ddgksf2013
高德地图_amdc处理 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amdc.js,pattern=^https?:\/\/amdc\.m\.taobao\.com,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_底部tab栏角标@ddgksf2013
高德地图_底部tab栏角标 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/message\/notice\/list,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_首页右中广告@ddgksf2013
高德地图_首页右中广告 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/frogserver\/aocs\/updatable,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_附近页面@ddgksf2013
高德地图_附近页面 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/nearbyrec_smart,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_打车页面处理@ddgksf2013
高德地图_打车页面处理 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/promotion-web\/resource,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_首页底部处理@ddgksf2013
高德地图_首页底部处理 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/main-page,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_开屏广告@ddgksf2013
高德地图_开屏广告 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/valueadded\/alimama\/splash_screen,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_首页顶部推广@ddgksf2013
高德地图_首页顶部推广 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/msgbox\/pull,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_我的页面@ddgksf2013
高德地图_我的页面 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaas,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 高德地图_搜索框热词@ddgksf2013
高德地图_搜索框热词 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js,pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/new_hotword,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% *.amap.com