#!name= Keep 净化
#!desc= 应用净化去广告
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/KeepStyle.module

// ==UserScript==
// @ScriptName        Keep 净化
// @Author            @ddgksf2013
// @ForHelp           若有屏蔽广告的需求，可公众号后台回复APP名称
// @WechatID          公众号墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2023-01-12
// @Function          应用净化去广告
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.4
// @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/KeepStyle.conf
// ==/UserScript==

[URL Rewrite]
# > 屏蔽部分启动弹窗
^https?:\/\/api\.gotokeep\.com\/kprime\/v\d\/popups\/primeGuide _ reject
# > 屏蔽开屏广告请求
^https?:\/\/kad\.gotokeep\.com\/op-engine-webapp\/v\d\/ad _ reject
# > 屏蔽青少年弹窗
^https?:\/\/api.gotokeep.com/cauchy/growth/init _ reject
# > 屏蔽搜索栏自动填充词
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/default\/keyword\/list _ reject
# > 屏蔽热词
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/hotword\/list _ reject
# > 屏蔽hotCourse
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/hotCourse\/list _ reject
# > 屏蔽adwebapp
^https?:\/\/api\.gotokeep\.com\/op-engine-webapp\/v\d\/ad _ reject
# > 屏蔽广告预加载
^https?:\/\/api\.gotokeep\.com\/ads\/v\d\/ads\/preload _ reject
# > 屏蔽adbox
^https?:\/\/api\.gotokeep\.com\/training\/box\/config _ reject
# > 屏蔽更新
^https?:\/\/api\.gotokeep\.com\/anno\/v\d\/upgrade\/check _ reject

[Script]
# > 我的页面去推广
我的页面去推广 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/keepStyle.js,pattern=^https?:\/\/api\.gotokeep\.com\/athena\/v\d\/people\/my$,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 应用底部栏净化
应用底部栏净化 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/keepStyle.js,pattern=^https?:\/\/api\.gotokeep\.com\/config\/v\d\/basic,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 发现页处理
发现页处理 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/keepStyle.js,pattern=^https?:\/\/api\.gotokeep\.com\/homepage\/v\d\/tab,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 课程预览页广告
课程预览页广告 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/keepStyle.js,pattern=^https?:\/\/api\.gotokeep\.com\/nuocha\/course\/v2\/\w+\/preview,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 我的运动页面去除下方推荐
我的运动页面去除下方推荐 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/keepStyle.js,pattern=https://api.gotokeep.com/sportpage/sport/v3/mysport,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% api.gotokeep.com, kad.gotokeep.com