#!name= 酷我音乐、酷我音乐纯净版[ SVIP+净化 ]
#!desc= 史上最全酷我音乐净化加VIP音乐畅听，已兼容酷我原版与酷我畅听版
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/kuwo.module

# ==UserScript==
# @ScriptName        酷我音乐、酷我音乐纯净版[ SVIP+净化 ]
# @Attention         史上最全酷我音乐净化加VIP音乐畅听，已兼容酷我原版与酷我畅听版
# @Author            @ddgksf2013
# @WechatID          公众号墨鱼手记
# @TgChannel         https://t.me/ddgksf2021
# @Contribute        https://t.me/ddgksf2013_bot
# @Feedback          📮 ddgksf2013@163.com 📮
# @UpdateTime        2023-04-12
# @Attention         使用中若有问题请发邮件！
# @Suitable          自行观看“# > ”注释内容
# @Attention         如需引用请注明出处，谢谢合作！
# @Version           V2.0.44
# @ScriptURL         https://gist.githubusercontent.com/ddgksf2013/0f76e952f0c4a2579932f45a209b40c3/raw/Kuwo.conf
# ==/UserScript==

# 本重写仅限本人使用，严禁传播
# 解决酷我发热问题，在本地添加下面的分流或者关闭广告终结者Anti分流
# host-suffix, kuwo.cn, direct

[URL Rewrite]
# ～ BiliBili_哔哩哔哩_屏蔽广告浮窗@ddgksf2013
# > 酷我音乐_通用广告请求
https?:\/\/vip1\.kuwo\.cn\/vip\/activity\/kwMemberDay _ REJECT-200
# > 酷我音乐_屏蔽热词
https?:\/\/hotword\.kuwo\.cn\/hotword\.s _ REJECT-DICT
# > 酷我音乐_通用广告请求
https?:\/\/vip1\.kuwo\.cn\/vip_adv\/ _ REJECT-DICT
# > 酷我音乐_通用广告请求
https?:\/\/wapi\.kuwo\.cn\/openapi\/v1\/app\/pasterAdvert _ REJECT-200
# > 酷我音乐_应用内弹窗及右下角
^https?:\/\/mobilead\.kuwo\.cn\/ _ REJECT-200
# > 酷我音乐_开屏广告
https?:\/\/rich\.kuwo\.cn\/AdService url reject-200

[Script]
# > 酷我音乐_搜索框处理
酷我音乐_搜索框处理 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/searchrecterm\.kuwo\.cn\/recterm\.s,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_去除首页轮播广告和tips
酷我音乐_去除首页轮播广告和tips = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/mgxhtj\.kuwo\.cn\/mgxh\.s,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_去除会员页广告
酷我音乐_去除会员页广告 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/appi\.kuwo\.cn\/kuwopay\/vip-tab\/page\/cells,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_去除会员页顶部广告tab
酷我音乐_去除会员页顶部广告tab = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/appi\.kuwo\.cn\/kuwopay\/vip-tab\/setting,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_数字专辑
酷我音乐_数字专辑 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/musicpay\.kuwo\.cn\/music\.pay\?newver,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_听书权限接口1
酷我音乐_听书权限接口1 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/.*\.(kuwo|lrts)\.(cn|me)\/a\.p,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_听书权限接口2
酷我音乐_听书权限接口2 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/.*\.kuwo\.cn\/v2\/api\/pay\/vip\/extraVipStatus,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_新版vip接口1
酷我音乐_新版vip接口1 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/enc\/user\/vip\?op=ui,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_新版vip接口2
酷我音乐_新版vip接口2 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/v2\/userbase\/vip\?op=get,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_旧版vip接口
酷我音乐_旧版vip接口 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/v2\/user\/vip($|\?op=ui),max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_皮肤解锁
酷我音乐_皮肤解锁 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/v2\/theme,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
# > 酷我音乐_无损下载[限纯净版]小火箭可能还不支持修改请求头
酷我音乐_无损下载 = type=http-response,script-path=https://github.com/ddgksf2013/dev/raw/main/kuwomusic.js,pattern=^https?:\/\/musicpay\.kuwo\.cn\/music\.pay\?ui,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true


[MITM]
hostname = %APPEND% *.kuwo.cn, *.lrts.me
