#!name= Spotify
#!desc= 解锁部分premium,建议重新登录,并清除缓存,音质不能设置为超高。
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/Spotify.module

########################################
#应用名称：  Spotify
#脚本作者：  app2smile
#更新时间：  2022-06-13
#使用说明：  解锁部分premium,建议重新登录,并清除缓存,音质不能设置为超高。

#脚本功能：  1.去除播放广告；2.歌手/专辑列表正常展示；3.去除随机播放
#通知频道：  https://t.me/ddgksf2021
#作者库地：  https://github.com/app2smile/rules
#脚本地址：  https://github.com/ddgksf2013/Rewrite/raw/master/UnlockVip/Spotify.conf
########################################

[Script]
Spotify1 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
Spotify2 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
Spotify3 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
Spotify3 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% spclient.wg.spotify.com