#!name= Keep 净化
#!desc= 应用净化去广告
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/KeepStyle.conf

// ==UserScript==
// @ScriptName        小红书去广告
// @Author            @ddgksf2013
// @ForHelp           若有屏蔽广告的需求，可公众号后台回复APP名称
// @WechatID          公众号墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @MainFunction      去开屏、瀑布流、启动服务广告及一些隐私、广告、青少年请求，去水印及功能增强
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2023-06-08
// @Function          去广告配置（自用，不定期更新）
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/XiaoHongShu.conf
// ==/UserScript==

[URL Rewrite]
# > 小红书_通用广告请求@ddgksf2013
^https?:\/\/www\.xiaohongshu\.com\/api\/sns\/v\d\/(tag\/)?ads _ reject-dict
# > 小红书_隐私屏蔽@ddgksf2013
^https?:\/\/referee\.xiaohongshu\.com\/v\d\/stateReport _ reject-dict
# > 小红书_Switches@ddgksf2013
^https?:\/\/pages\.xiaohongshu\.com\/data\/native\/matrix_switches _ reject-dict
# > 小红书_青少年请求@ddgksf2013
^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/user\/teenager\/status _ reject-dict
# > 小红书_启动引导@ddgksf2013
^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/guide\/home_guide _ reject-dict

[Script]
# > 小红书_视频播放页商品推广@ddgksf2013
小红书_视频播放页商品推广 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/note\/widgets,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_短视频流去水印+强制开启保存功能@ddgksf2013
小红书_短视频流去水印 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/note\/redtube\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_信息流视频去水印+强制开启保存功能@ddgksf2013
小红书_信息流视频去水印 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/note\/videofeed\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_信息流图片去水印@ddgksf2013
小红书_信息流图片去水印 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/note\/feed\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_开屏广告@ddgksf2013
小红书_开屏广告 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/system_service\/splash_config,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_首页瀑布流@ddgksf2013
小红书_首页瀑布流 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/homefeed\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_启动处理@ddgksf2013
小红书_启动处理 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/system_service\/config\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_热搜发现@ddgksf2013
小红书_热搜发现 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/search\/hot_list,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_默认填词@ddgksf2013
小红书_默认填词 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/search\/hint,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_去除购物@ddgksf2013
小红书_去除购物 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/homefeed\/categories,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# > 小红书_猜你想搜@ddgksf2013
小红书_猜你想搜 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/redbook_json.js,pattern=^https?:\/\/edith\.xiaohongshu\.com\/api\/sns\/v\d\/search\/trending,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% edith.xiaohongshu.com, www.xiaohongshu.com, pages.xiaohongshu.com, referee.xiaohongshu.com