#!name= 喜马拉雅净化[墨鱼版]
#!desc= 喜马拉雅净化
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/Ximalaya.module

# ==UserScript==
# @ScriptName        喜马拉雅净化[墨鱼版]
# @Author            @ddgksf2013
# @ForHelp           若有屏蔽广告的需求，可公众号后台回复APP名称
# @WechatID          公众号墨鱼手记
# @TgChannel         https://t.me/ddgksf2021
# @Contribute        https://t.me/ddgksf2013_bot
# @Feedback          📮 ddgksf2013@163.com 📮
# @UpdateTime        2023-05-03
# @Attention         如果广告仍然存在，请清除缓存或卸载应用重新安装
# @Function          去广告配置（自用，不定期更新）
# @Suitable          自行观看“# > ”注释内容
# @Attention         如需引用请注明出处，谢谢合作！
# @Version           V1.0.25
# @ScriptURL         https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/Ximalaya.conf
# ==/UserScript==

[URL Rewrite]
# ～ XiMaLaYa_喜马拉雅_修复轮播Ad失效Bug@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/discovery-feed\/focus\/queryF _ reject
# ～ XiMaLaYa_喜马拉雅_播放页_Live@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/mobile-playpage\/view\/ _ reject
# ～ XiMaLaYa_喜马拉雅_MyInfo红点提醒@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/chaos-notice-web\/v1\/message\/preview\/list _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽大红包Tips@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/social-web\/bottomTabs\/dynamicEntrance\/status _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽gif弹窗Ad@ddgksf2013
^https?:\/\/.*\.xmcdn\.com\/\w{8}\/\w{4}-\w{16}\/.+gif$ _ reject
# ～ XiMaLaYa_喜马拉雅_gslb@ddgksf2013
^https?:\/\/gslb.*\.xima.*\.com\/ _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽Aged请求@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/(dog-portal\/checkOld|(child-mobile\/child|aged-mobile\/aged)\/mode\/query) _ reject
# ～ XiMaLaYa_喜马拉雅_部分Tab弹窗@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/discovery-feed\/isShowUserGiftPendant _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽红点提示@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/mobile-user\/unread _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽minor请求@ddgksf2013
^https?:\/\/.*\.xima.*\.com/mobile-user/minorProtection/pop _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽隐私搜集@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/collector\/xl\/v\d _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽版本更新@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/butler-portal\/versionCheck _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽开屏广告@ddgksf2013
^https?:\/\/(adse\.wsa|adse|adbehavior|xdcs-collector)\.xima.*\.com\/.* _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽位置请求@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/mobile\/discovery\/v\d\/location _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽热搜词@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/hotWord _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽搜索框定时_Ad@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/guideWord _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽实时Ad请求@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/api\/v\d\/adRealTime _ reject
# ～ XiMaLaYa_喜马拉雅_屏蔽ting_Ad@ddgksf2013
^https?:\/\/.*\.xima.*\.com\/ting\/(loading|feed|home)? _ reject


[Script]
# ～ XiMaLaYa_喜马拉雅_首页顶部去除直播@ddgksf2013
XiMaLaYa_喜马拉雅_首页顶部去除直播 = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/ximalaya_json.js,pattern=^https?:\/\/.*\.xima.*\.com\/discovery-category\/customCategories,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# ～ XiMaLaYa_喜马拉雅_屏蔽首页横幅_Ad@ddgksf2013
XiMaLaYa_喜马拉雅_屏蔽首页横幅_Ad = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/ximalaya_json.js,pattern=^https?:\/\/.*\.xima.*\.com\/focus-mobile\/focusPic,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# ～ XiMaLaYa_喜马拉雅_屏蔽首页动态_Ad@ddgksf2013
XiMaLaYa_喜马拉雅_屏蔽首页动态_Ad = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/ximalaya_json.js,pattern=^https?:\/\/.*\.xima.*\.com\/discovery-feed\/v\d\/mix,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# ～ XiMaLaYa_喜马拉雅_屏蔽Tab页滚动_Ad@ddgksf2013
XiMaLaYa_喜马拉雅_屏蔽Tab页滚动_Ad = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/ximalaya_json.js,pattern=^https?:\/\/.*\.xima.*\.com\/discovery-category\/v\d/category,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

# ～ XiMaLaYa_喜马拉雅_去除我的页面Ad_Tag@ddgksf2013
XiMaLaYa_喜马拉雅_去除我的页面Ad_Tag = type=http-response,script-path=https://github.com/ddgksf2013/Scripts/raw/master/ximalaya_json.js,pattern=^https?:\/\/.*\.xima.*\.com\/mobile-user\/v\d\/homePage,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% *.xima*.com, *.xmcdn.com