#!name= Youtube Block AD
#!desc= 用于视频、瀑布流、搜索、播放页、短视频及贴片广告、视频自动PIP、后台播放、自动翻译，不适用允许 UDP 转发的节点及 Premium
#!homepage= https://github.com/ddgksf2013
#!author= ddgksf2013
#!url= https://raw.githubusercontent.com/wen704/rules/beta/ddgksf2013/YoutubeAds.module

########################################
#应用名称：  Youtube Block AD
#脚本作者：  @DivineEngine, @app2smile, @Maasea, @VirgilClyne
#更新时间：  2023-06-05
#使用说明：  用于视频、瀑布流、搜索、播放页、短视频及贴片广告、视频自动PIP、后台播放、自动翻译，不适用允许 UDP 转发的节点及 Premium
#使用说明：  如果视频广告仍然存在，请在QuantumultX配置文件的[general]下添加 udp_drop_list=443
#通知频道：  https://t.me/ddgksf2021
#原始仓库：  https://github.com/DivineEngine
#原始仓库：  https://github.com/Maasea
#原始仓库：  https://github.com/app2smile
#重写地址：  https://github.com/ddgksf2013/Rewrite/raw/master/AdBlock/YoutubeAds.conf
########################################

[URL Rewrite]
# ======= 视频广告请求 ======= #
#(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) url 302 $1$2$3
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ REJECT-200

# ======= 通用广告请求 ======= #
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ REJECT-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ REJECT-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ REJECT-200

[Script]
# ======= 视频PIP|后台播放|瀑布流|搜索页|播放页|短视频|贴片广告  ======= #
YoutubeAds1 = type=http-response,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.request.beta.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence)\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

YoutubeAds2 = type=http-response,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/dist/youtube.response.beta.js,pattern=^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting)\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% -redirector*.googlevideo.com, *.googlevideo.com, www.youtube.com, s.youtube.com, youtubei.googleapis.com