#!name= 贴吧去广告
#!desc= 开屏广告;推荐和吧内帖子列表的直播及广告;详情页直播/关联商品/广告;看图模式广告;首页和帖子详情页右下角悬浮广告;部分吧内的置顶/最新中间的广告/head图片广告/head直播
#!homepage= https://github.com/app2smile
#!author= app2smile
#!url= https://raw.githubusercontent.com/wen704/rules/beta/app2smile/tieba-qx.module

# 原作者链接 https://raw.githubusercontent.com/app2smile/rules/master/module/tieba-qx.conf

# 贴吧去广告-qx(>=iOS15)
# qx加载本重写前,须同时加载对应的贴吧分流,否则不能完全去广告
# 仓库地址 https://github.com/app2smile/rules
# 开屏广告;推荐和吧内帖子列表的直播及广告;详情页直播/关联商品/广告;看图模式广告;首页和帖子详情页右下角悬浮广告;部分吧内的置顶/最新中间的广告/head图片广告/head直播

[Script]
贴吧去广告1 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/tieba-json.js,pattern=^http(s:\/\/tiebac|:\/\/c\.tieba)\.baidu\.com\/(c\/f\/(frs\/(page|threadlist|generalTabList)|pb\/page|excellent\/personalized)$|tiebaads\/commonbatch|c\/s\/sync$),max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

贴吧去广告2 = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/tieba-proto.js,pattern=^http(s:\/\/tiebac|:\/\/c\.tieba)\.baidu\.com\/c\/f\/(frs\/(page|threadlist|generalTabList)|pb\/page|excellent\/personalized)\?cmd,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% tiebac.baidu.com